export default {
  OVERLAY: {
    SHOW: 'OVERLAY_SHOW',
    HIDE: 'OVERLAY_HIDE'
  },
  MENU: {
    CHANGE_CHAPTER: 'MENU_CHANGE_CHAPTER',
    CHANGE_SECTION: 'MENU_CHANGE_SECTION'
  },
  TOME: {
    CHAPTER: {
      SELECT: 'TOME_CHAPTER_SELECT'
    },
    SECTION: {
      SELECT: 'TOME_SECTION_SELECT'
    }
  },
};
